### ISSUE TITLE
Add alias for address feature

### ISSUE THREAD

**Issue by SheldonYS** [virtualeconomy/v-wallet-gui#125]
Add address management in **setting**. In address management, we store `address -> alias` dictionary. If address can be find in dictionary, the address shows as "alias (address)" in transaction panel. If some place do not have enough space, just show "alias".

**Comment by SheldonYS** [comment]
Here is UI Design:
<img width="190" alt="Screenshot 2020-01-14 at 11 19 10 AM" src="https://user-images.githubusercontent.com/41148850/72312474-3392c200-36c3-11ea-9805-f7817f4922a3.png">
<img width="509" alt="Screenshot 2020-01-14 at 11 23 53 AM" src="https://user-images.githubusercontent.com/41148850/72312480-3ab9d000-36c3-11ea-9add-bb880d98113d.png">

If address matches the alias name, it will show like this:
<img width="326" alt="Screenshot 2020-01-14 at 11 34 09 AM" src="https://user-images.githubusercontent.com/41148850/72312575-7fde0200-36c3-11ea-970d-415ed49c9295.png">
<img width="516" alt="Screenshot 2020-01-14 at 11 35 33 AM" src="https://user-images.githubusercontent.com/41148850/72312576-7fde0200-36c3-11ea-8d05-1ec4061f4625.png">
<img width="511" alt="Screenshot 2020-01-14 at 11 39 04 AM" src="https://user-images.githubusercontent.com/41148850/72312577-7fde0200-36c3-11ea-82f0-c514fb0ef510.png">
<img width="523" alt="Screenshot 2020-01-14 at 11 40 36 AM" src="https://user-images.githubusercontent.com/41148850/72312578-80769880-36c3-11ea-98d2-90bfeedec21b.png">

**Comment by PKUzjw** [comment]
already has been implemented
