### ISSUE TITLE
The "Z-index" for "add token" is too high

### ISSUE THREAD

**Issue by SheldonYS** [virtualeconomy/v-wallet-gui#191]
The  "add token" should be higher than panel but lower than modal and button. Please change "Z-index" for "add token".
<img width="687" alt="Screenshot 2019-05-21 at 10 35 07 AM" src="https://user-images.githubusercontent.com/41148850/58064336-367cf780-7bb4-11e9-8d44-3535cb833d3a.png">

**Comment by Haynar216** [comment]
This issue has been resolved in the latest pr which has been merged
