### ISSUE TITLE
Split Token Issue

### ISSUE THREAD

**Issue by SheldonYS** [virtualeconomy/v-wallet-gui#256]
After Split Token, unity is not update until click "Get Token Info". User will confuse about their balance if not click "Get Token Info".

**Comment by PKUzjw** [comment]
After testing, I found it needs several seconds to automatically update unity and balance, but users do not need to manually click "Get Token Info" to update them.

**Comment by SheldonYS** [comment]
In my testing, the unity did not update until I click "Get Token Info"

**Comment by SheldonYS** [comment]
fixed by #275
