### ISSUE TITLE
Identify active leasing in Minting Tab

### ISSUE THREAD

**Issue by SheldonYS** [virtualeconomy/v-wallet-gui#261]
Seeing from Minting Tab, there is no difference between active leasing TX and cancelled leasing TX. It should showing different here.

**Comment by SheldonYS** [comment]
Make difference like this.
<img width="521" alt="Screenshot 2019-07-01 at 11 48 53 AM" src="https://user-images.githubusercontent.com/41148850/60409536-ab514180-9bf6-11e9-8bae-d12e9dda4879.png">

**Comment by Haynar216** [comment]
#265
