### ISSUE TITLE
add type filter in Transaction Tab

### ISSUE THREAD

**Issue by SheldonYS** [virtualeconomy/v-wallet-gui#262]
As Transaction Tab can show 1000 records at most, there should have type filter in Transaction Tab. Please add the filter.
<img width="178" alt="Screenshot 2019-07-01 at 11 44 56 AM" src="https://user-images.githubusercontent.com/41148850/60409582-ce7bf100-9bf6-11e9-90c1-aa5f801f6c91.png">

**Comment by Haynar216** [comment]
Solved in #267

**Comment by SheldonYS** [comment]
Use new API `Get /transactions/list` with `txType` to refactor this feature.
<img width="979" alt="Screenshot 2019-08-15 at 1 09 10 PM" src="https://user-images.githubusercontent.com/41148850/63074009-ec5ea480-bf5d-11e9-9378-376271364adc.png">
