### ISSUE TITLE
Wrong destroy available 

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-wallet-gui#285]
Please check the available list here. Current supply is the up bound of the destroy available. But the exact one is the token balance of issuer.

https://github.com/virtualeconomy/v-wallet-gui/blob/ac6105e3384d463cb96d5a59a1c31c1e24ec4b06/src/components/home/elements/IssueAndBurnToken.vue#L50-L55

**Comment by SheldonYS** [comment]
fixed in #286
