### ISSUE TITLE
[discussion] unity of the split function

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-wallet-gui#308]
it is better to fix the split unity in 10^n range, or find some solution for some special unity.

for example if set the unity to 13,
<img width="474" alt="WX20190910-120344@2x" src="https://user-images.githubusercontent.com/38449461/64583453-8bdb4f80-d3c3-11e9-9b76-b762e97ad5bb.png">

**Comment by SheldonYS** [comment]
I think we'd better limit wallet split unity within 10^n range.
<img width="505" alt="Screenshot 2019-10-31 at 11 19 23 AM" src="https://user-images.githubusercontent.com/41148850/67916372-75d25a00-fbd0-11e9-9f35-58d3af817c69.png">

BTW, if Token do not support split, the "Split Token" Button should be hide. The "support split" status should be recorded when "Add Token".
<img width="244" alt="Screenshot 2019-10-31 at 11 25 51 AM" src="https://user-images.githubusercontent.com/41148850/67916682-77e8e880-fbd1-11e9-9f2f-9d431403f13d.png">

**Comment by SheldonYS** [comment]
fixed by #343
