### ISSUE TITLE
show transaction fee case

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-wallet-gui#314]
1. it seems that the colour of the `Tx Fee: - 0.1 VSYS` is related with the colour of icon. but execute contract one is used as red(same as payment), right?

2. if transaction fee equal to zero, it omit the Tx Fee part (incoming and canceled incoming lease), however, for execute contract function transaction (someone send token to me), `Tx Fee: - 0.00 VSYS` is displayed.

**Comment by PKUzjw** [comment]
Tx Fee: -0.3 VSYS is displayed after executing contract function transaction
