### ISSUE TITLE
Consistency with cold wallet

### ISSUE THREAD

**Issue by Haynar216** [virtualeconomy/v-wallet-gui#32]
1.Due to the website wallet should always match the cold wallet, tip of updating should show up if a new cold wallet version is released when user scan the qr code of cold wallet by the website wallet.

2.The public key of cold wallet is not essential to import a cold wallet.

**Comment by SheldonYS** [comment]
For 1, it is solved in current version.
For 2, this feature might not implement. The public key will be used for some new feature in later version.
