### ISSUE TITLE
Move "Start Leasing (Cancelled)" transaction to the transaction tab

### ISSUE THREAD

**Issue by georgygv** [virtualeconomy/v-wallet-gui#386]
Hello, this is my first contribution here. Since I started using leasing I have many canceled leasing transactions in the Minting tab, and now it makes a bit confusing to see my leasing which is currently active, because in the Minting tab I can't filter type of transactions like in  the Transactions tab. My suggestion is to move  "Start leasing (canceled)" transactions to the Transactions tab, all transaction records should be there after all, otherwise we just have double records in both tabs. And make the Minting section as the one that monitors all active leasing (By the way is it possible to rename "Start leasing" to "Active Leasing" ?!)

**Comment by SheldonYS** [comment]
The usage of two tabs are different. Transactions Tab is used for balance accounting. It shows all transactions with fee, including "leasing" and "canceled leasing". Minting Tab  is used for lease management. It does not show "canceled lease" records, so adding "(Canceled)" word to indicate whether it is active or not. Rename "Start leasing" is under consideration. Anyway, thanks for your advise!

**Comment by georgygv** [comment]
> Minting Tab is used for lease management. It does not show "canceled lease" records, so adding "(Canceled)" word to indicate whether it is active or not.

Minting tab shows **"Start Leasing (Cancelled)"** records, maybe making a filter option to sort type of records in the minting tab would help. But anyway, I'm not a developer but I wish would make Transacations tab as "Records" to keep all kind of records and leave Minting tab as the one that only  shows and monitors Active leasing. In this case both tabs would have a very distinct roles from each other, one keeps records and only records, another one for management and monitoring active leasing. Alright, guys, keep up the good work, that was my tiny contribution.
![image](https://user-images.githubusercontent.com/26365594/76385557-f5e9a700-639c-11ea-957e-87cf49c495c9.png)

**Comment by SheldonYS** [comment]
Thanks for your advisement. But before call RPC to get lease record, we did not know which lease is canceled. If just hide the canceled lease, some users will complain, "I want to get 10 lease records but why wallet just show me 4 lease records?" We cannot satisfy all user's requirements, so we just make what wallet showing as more reasonable as possible.
