### ISSUE TITLE
new release upgrade

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-wallet-gui#394]
since we will activate some new contracts in the new release, some old situations will be changed.  v wallet should transfer to compatible mode.

1. transaction records should separate the contract type and keep the token transactions (or just simply list the other execute contract function transactions). 
2. token contract, user can use the deposit, withdraw functions to deposit token to contract account, and withdraw the token from the contract account, such transactions may need to re-explain the details.
3. a fixed system transfer contract will be activated and the user can deposit/withdraw VSYS with a contract account.

**Comment by SheldonYS** [comment]
implement by #395
