### ISSUE TITLE
VSYS Wallet Support

### ISSUE THREAD

**Issue by sagiusti** [virtualeconomy/v-wallet-gui#399]
Hello,

I have a Hot and Cold VSYS wallet and I have leased out VSYS that I am trying to retrieve that somehow ended up in a cold wallet. When I try to send the VSYS out of the Cold Wallet I get the following error - "This cold wallet has invalid public key! If you import this cold wallet manually, please delete it and import it again."  Due to this error I am unable to transfer VSYS out of this Cold Wallet into my VSYS Hot Wallet.  I was able to retrieve the Hot wallet lease out token but I'm not able to retrieve my leased out Cold wallet tokens. Is support available?

Thanks.

Steve 
[200813 VSYS Wallet Error.docx](https://github.com/virtualeconomy/v-wallet-gui/files/5072170/200813.VSYS.Wallet.Error.docx)

**Comment by Haynar216** [comment]
There are two ways to suggest trying it
1. In your hot wallet, delete this cold wallet and monitor it again
![image](https://user-images.githubusercontent.com/32302909/91795874-6a691880-ec51-11ea-96bc-cfb7768f02d0.png)

2. Restore an account in the hot wallet through the seed of your cold wallet, so you can complete the transaction directly through the hot wallet
![image](https://user-images.githubusercontent.com/32302909/91795956-9f756b00-ec51-11ea-953b-1343955f93fe.png)

No matter what, you must remember your seed, it is the key to get back your account
