### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by pasrkb** [virtualeconomy/v-wallet-gui#409]
@pkubear 
Today my balance of VSYS shows as 50,840. On 8/23 it was 243,266. On 8/18 it was 118,261. Why does it vary?

**Comment by SheldonYS** [comment]
What's your V wallet address?

**Comment by pasrkb** [comment]
ARH7qKfAfqCwFsBC34exzBGa2iTZNKrFbhy

**Comment by SheldonYS** [comment]
ARH7qKfAfqCwFsBC34exzBGa2iTZNKrFbhy is supernode address which maintained by bullseye. Are you from bullseye team?

**Comment by pasrkb** [comment]
Not that I know of

**Comment by SheldonYS** [comment]
It seems you does not see the your owned address. Please find your address in left panel of wallet. 
<img width="836" alt="Screenshot 2020-11-25 at 10 53 22 AM" src="https://user-images.githubusercontent.com/41148850/100177206-97556080-2f0c-11eb-8a3b-011c868e9db5.png">

**Comment by pasrkb** [comment]
Yes, I can access the account, and when I do and open my Cold Wallet, like I said at the beginning of this dialogue, it currently shows a balance of VSYS as 50,840. But like I said, in 8/23 it was 243,266. And on 8/18 it was 118,261. I am asking why does it vary?

**Comment by pasrkb** [comment]
I just opened the account and the balance shows as follows in the screen shot I just took of the Cold Wallet:

[Wallet 11-24-20 screen shot2.docx](https://github.com/virtualeconomy/v-wallet-gui/files/5594180/Wallet.11-24-20.screen.shot2.docx)

**Comment by SheldonYS** [comment]
You can monitor this address as monitor cold wallet address but in fact you does not own this address. The address ARH7qKfAfqCwFsBC34exzBGa2iTZNKrFbhy, in fact, is controlled by bullseye team.

**Comment by pasrkb** [comment]
How do I determine/see my balance? How is it that I can monitor an account controlled by bullseye team?

**Comment by SheldonYS** [comment]
In blockchain world, once you own a private key of account, you own the account. Balance and transaction history are open to public inquiries.
You can monitor any address in wallet in the following way:
<img width="912" alt="Screenshot 2020-11-25 at 11 19 26 AM" src="https://user-images.githubusercontent.com/41148850/100179137-4c3d4c80-2f10-11eb-99b8-952c45f08ab2.png">

**Comment by pasrkb** [comment]
Is the private key the same as the private 15 word phrase or is it the ID?

**Comment by SheldonYS** [comment]
private key is not 15 word phrase, but 15 word phrase can generate the private key.
So own 15 word phrase = own private key = own the account.

**Comment by pasrkb** [comment]
At beginning of our conversation you asked for my V wallet address. I found it in my account information. It is AR4yLFjUam1hbwfg8LvuPVPXLmWTpaN9tXf . Does that enable you to answer my original question?

**Comment by SheldonYS** [comment]
Your address AR4yLFjUam1hbwfg8LvuPVPXLmWTpaN9tXf is 0. It does not vary.

**Comment by pasrkb** [comment]
I sent 2872 VSYS to the wallet a year ago. Can you determine what happened to them with the correct information?

**Comment by SheldonYS** [comment]
Any proof that you sent 2872 VSYS? Could you provide transaction ID?

**Comment by pasrkb** [comment]
ID		7w9sqUaE7Tz9hUAyyaNmBsoanCmaFjjhe3Rd8ewnJSQa

**Comment by SheldonYS** [comment]
You use AR51aBcTbWn2uGvJ8wVvCxctQw9qp6TZaVs lease to bulleyes, not sending 2872 VSYS to AR4yLFjUam1hbwfg8LvuPVPXLmWTpaN9tXf.
https://explorer.v.systems/transactions/7w9sqUaE7Tz9hUAyyaNmBsoanCmaFjjhe3Rd8ewnJSQa

**Comment by pasrkb** [comment]
Did I make a mistake? Is lease the same as staking?

**Comment by SheldonYS** [comment]
Yes. lease = minting = staking.
Last year, you used your address "AR51a...p6TZaVs" to lease 2872 VSYS to bulleyes "ARH7qK...NKrFbhy", not sending to "AR4yLF...TpaN9tXf".

**Comment by pasrkb** [comment]
So my 2872 VSYS are among the balance of 268061.53624183 in the bulleyes account? Can I see my balance segregated from the rest? And how do I see my balance and what has accumulated from leasing?

**Comment by pasrkb** [comment]
Are you still there?

**Comment by SheldonYS** [comment]
Your lease are among the 116785428 VSYS.
<img width="612" alt="Screenshot 2020-11-25 at 1 36 53 PM" src="https://user-images.githubusercontent.com/41148850/100187657-86fcb000-2f23-11eb-8376-3706ea99c8a6.png">

The wallet cannot get accumulated reward amount, but you can export the transaction history and calculate by MS Excel yourself.
<img width="616" alt="Screenshot 2020-11-25 at 1 42 22 PM" src="https://user-images.githubusercontent.com/41148850/100188225-bd86fa80-2f24-11eb-803e-2890687947ec.png">
