### ISSUE TITLE
transaction won't go through

### ISSUE THREAD

**Issue by ptaharchitect** [virtualeconomy/v-wallet-gui#411]
a friend sent me some crypto tokens and they won't go into my hot wallet on v
![Screen Shot 2020-12-07 at 12 21 49 PM](https://user-images.githubusercontent.com/75636420/101389301-d5e10880-3886-11eb-93a6-a7d10bf61e80.png)
![Screen Shot 2020-12-07 at 12 21 56 PM](https://user-images.githubusercontent.com/75636420/101389309-d8dbf900-3886-11eb-8675-22ec68d41ef1.png)

systems

**Comment by SheldonYS** [comment]
Ask your friend to tell you the token ID. Then you need add the token in watch list.
