### ISSUE TITLE
How do I change browsers for the wallet?

### ISSUE THREAD

**Issue by rmherran** [virtualeconomy/v-wallet-gui#416]
How do I change browsers for the wallet?  I want to migrate from using Mozilla to using Chrome browser, now from Chrome I get this message; 

"The browser cannot find any account for current domain"

How can I fix this, so I can use Chrome browser?

Ralph Michael Herran
704 728-0188

**Comment by SheldonYS** [comment]
You can find your seed (15 words) in Account in Mozilla.
<img width="208" alt="Screenshot 2021-01-18 at 11 31 29 AM" src="https://user-images.githubusercontent.com/41148850/104869447-0dac9700-5981-11eb-8ced-335b8deaaaa9.png">
<img width="496" alt="Screenshot 2021-01-18 at 11 31 55 AM" src="https://user-images.githubusercontent.com/41148850/104869469-1604d200-5981-11eb-9a67-314ed1fa9fe6.png">
And then restore account with 15 words in Chrome.
<img width="665" alt="Screenshot 2021-01-18 at 11 36 27 AM" src="https://user-images.githubusercontent.com/41148850/104869654-827fd100-5981-11eb-89d7-e60b78f65b95.png">

**Comment by rmherran** [comment]
Sheldon,

Do I need to do this just to change browsers?  Right now it works in
Mozilla, but when I go to Chrome it does not work?

Mike

**Comment by SheldonYS** [comment]
> Sheldon, Do I need to do this just to change browsers? Right now it works in Mozilla, but when I go to Chrome it does not work? Mike
> […](#)

I do not in what step you meet problem in Chrome. Maybe this video could help you https://www.youtube.com/watch?v=8-6cHHKwcJs . The "restore account" demo is shown at 6:40 . You can follow the video and restore your account.

**Comment by rmherran** [comment]
Thanks!
