### ISSUE TITLE
vsys WALLET

### ISSUE THREAD

**Issue by pasrkb** [virtualeconomy/v-wallet-gui#418]

**Comment by pasrkb** [comment]
Can you please tell me how I see/access my balance of VSYS coins from among the total available balance in the cold wallet?

**Comment by SheldonYS** [comment]
Since cold wallet does not access network, you cannot see balance in cold wallet directly. But cold wallet can show the address. You can use hot wallet monitor your cold wallet address and see the balance. Or just type your address in explorer https://explorer.v.systems and see the address balance.
