### ISSUE TITLE
Leasing tokens

### ISSUE THREAD

**Issue by pasrkb** [virtualeconomy/v-wallet-gui#433]
When I end leasing with a supernode for VSYS, how long does it take for my tokens to be available to lease with a new supernode?

**Comment by SheldonYS** [comment]
Different Supernodes would have different staking policy. In general, you would not get staking reward until you have leased for 2 days. And the reward should greater than transaction fee. That means leasing amount should greater than about 5000 for daily  paid Supernode or greater than about 300 for weekly paid Supernode.
