### ISSUE TITLE
trying to pull transaction data from wallet.v.systems - time stamps are funky+

### ISSUE THREAD

**Issue by llapidus** [virtualeconomy/v-wallet-gui#436]
First, I can't export a year's worth of transactions, only the last 1000.
second, the time stamps that get exported look like this:
1614348892170000000
where the heck is the date in that?????

**Comment by SheldonYS** [comment]
This issue has been fixed in this PR https://github.com/virtualeconomy/v-wallet-gui/pull/437

**Comment by llapidus** [comment]
Cool! Thanks!

________________________________
