### ISSUE TITLE
IPX stop

### ISSUE THREAD

**Issue by Githubbuoy** [virtualeconomy/v-wallet-gui#443]

**Comment by Githubbuoy** [comment]
I no longer want IPX air dropped.  How do I end this?

**Comment by SheldonYS** [comment]
You can lease coins to a supernode which not support staking 2.0, for example, Bloq.
<img width="1237" alt="Screenshot 2021-03-30 at 3 59 10 PM" src="https://user-images.githubusercontent.com/41148850/112955626-37005500-9172-11eb-821c-cf64d4632ec1.png">

**Comment by Githubbuoy** [comment]
Thank you.
