### ISSUE TITLE
brower wallet sort

### ISSUE THREAD

**Issue by pkubear** [virtualeconomy/v-wallet-gui#47]
When done V sent or received, so far page shows "Sent" on the top and "received " on the bottom,  there is big  space in the middle. suggest: sort by table 2 lines one side is "sent" the other is " Received" then looks better than now.

**Comment by Haynar216** [comment]
Could you give me a screenshot or image of your issue?

**Comment by pkubear** [comment]
![sort](https://user-images.githubusercontent.com/29352742/51595557-ff624680-1f31-11e9-9953-38ae141ad6e5.JPG)

**Comment by SheldonYS** [comment]
> When done V sent or received, so far page shows "Sent" on the top and "received " on the bottom, there is big space in the middle. suggest: sort by table 2 lines one side is "sent" the other is " Received" then looks better than now.

Thanks for your advice. You meet special case that see `"Sent" on the top and "received " on the bottom`. In fact, the records is sorted by time, not by type. You are rich man that using wide screen so that see such a space. If using web wallet on **mobile**, the UI cannot adapt 2 columns.
