### ISSUE TITLE
add current block height

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-wallet-gui#55]
add current block height in hot wallet

**Comment by SheldonYS** [comment]
To avoid too many block height requests to wallet.v.systems, I suggest this feature only enable for professional user. So my solution is as following:
1. Add "Show Current Block Height" checkbox in the setting panel.
![h1](https://user-images.githubusercontent.com/41148850/51783888-ddf49b00-217b-11e9-9636-fb8f698c947d.jpg)
2. Once enabled this option, the block height will show in top right place. This value will be refresh every 12 seconds.
![h2](https://user-images.githubusercontent.com/41148850/51783910-2613bd80-217c-11e9-8582-2a56b73f2842.jpg)
