### ISSUE TITLE
receive button display on iPhone

### ISSUE THREAD

**Issue by MarvelZHANG** [virtualeconomy/v-wallet-gui#59]
When use safari on iPhone to browse the webpage, the receive button only shows an arrow, there is no text displayed.

**Comment by MarvelZHANG** [comment]
![capture](https://user-images.githubusercontent.com/35572000/51722129-5598cc00-208f-11e9-946b-3aa777334aa4.PNG)

**Comment by SheldonYS** [comment]
fixed in #67
