### ISSUE TITLE
separate network type

### ISSUE THREAD

**Issue by ncying** [virtualeconomy/v-wallet-gui#81]
separate the testnet wallet and mainnet wallet.

**Comment by SheldonYS** [comment]
I think the indicator Ⓣ or Ⓜ could add here.
<img width="618" alt="screenshot 2019-02-25 at 2 42 20 pm" src="https://user-images.githubusercontent.com/41148850/53319855-c0e3f100-390e-11e9-81af-d74edf67e0bd.png">
And show the network status on top of bar. 
<img width="725" alt="screenshot 2019-02-25 at 3 02 45 pm" src="https://user-images.githubusercontent.com/41148850/53319857-c3464b00-390e-11e9-9456-3eccd77d2145.png">
