### ISSUE TITLE
Big number in Json

### ISSUE THREAD

**Issue by zl730** [virtualeconomy/v-wallet-gui#83]
- An npm package called 'json-bignumber' may solve the problem.

  > 
  > **example** (Derived from https://www.npmjs.com/package/json-bignumber.) :
  > ```javascript
  > let input = '{"big":1234567890.123456789,"small":789.012}';
  >  
  > let obj1 = JSON.parse(input);
  > console.log("JSON", obj1.big.toString());  //'JSON', '1234567890.1234567'
  > //The number has lost the last 2 digits
  > let out1 = JSON.stringify(obj1);
  > console.log("JSON", out1);  //'JSON', '{"big":1234567890.1234567,"small":789.012}'
  >  
  > let obj2 = JSONBigNumber.parse(input);
  > console.log("JSONBigNumber", obj2.big.toString());  //'JSONBigNumber', '1234567890.123456789'
  > //No loss of precision
  > let out2 = JSONBigNumber.stringify(obj2);
  > console.log("JSONBigNumber", out2);  //'JSONBigNumber', '{"big":1234567890.123456789,"small":789.012}'
  > ```

-  Other option: [Add a new method to the BigNumber class. ](https://stackoverflow.com/questions/53256165/serialise-bigdecimal-bignumber-bigint-etc-to-and-from-json)

**Comment by SheldonYS** [comment]
Great finding!

**Comment by Haynar216** [comment]
Thanks a lot, it's now used in branch Precision
